/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capture_VMwareServerExt */

#ifndef _Included_capture_VMwareServerExt
#define _Included_capture_VMwareServerExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capture_VMwareServerExt
 * Method:    nConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_capture_VMwareServerExt_nConnect
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     capture_VMwareServerExt
 * Method:    nRevertVM
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_capture_VMwareServerExt_nRevertVM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     capture_VMwareServerExt
 * Method:    nDisconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_capture_VMwareServerExt_nDisconnect
  (JNIEnv *, jobject);


/*
 * Class:     capture_VMwareServerExt
 * Method:    nRunProgramInGuest
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_capture_VMwareServerExt_nRunProgramInGuest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     capture_VMwareServerExt
 * Method:    nWaitForToolsInGuest
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_capture_VMwareServerExt_nWaitForToolsInGuest
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
