/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capture_VMwareServer_VIX_ERROR_CODES */

#ifndef _Included_capture_VMwareServer_VIX_ERROR_CODES
#define _Included_capture_VMwareServer_VIX_ERROR_CODES
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
